<a href="https://colab.research.google.com/github/AlexsanderPessoa/Agro_bibliotecas/blob/main/agro_bibliotecas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

#logaritmo natural
print(math.log(31))

#especificando a base
print(math.log(31, 2))

3.4339872044851463
4.954196310386876


In [ ]:
#constantes
print(math.pi)
print(math.e)
print(math.inf)
print(math.nan)


3.141592653589793
2.718281828459045
inf
nan


In [ ]:
#eu só quero importat uma parte, e não toda a biblioteca, isso otimiza a memória
from math import pi
print(pi)

3.141592653589793


In [ ]:
from math import log, sqrt
print(log(1001, 3))
print(sqrt(400))

6.288619607278353
20.0


#metodo random


In [ ]:
import random as rd

In [ ]:
#aleatório de 0 e 1
print(rd.random())

0.4962079145505305


In [ ]:
#crio uma lista
num_alert = []
#para cada item dessa lista, de até 5 objetos
for i in range(5):
    #eu adiciono esse valor nessa lista, até dar 5 valores aleatórios de 0 a 1
    num_alert.append(rd.random())

print(num_alert)

[0.558127471089411, 0.7202052205371574, 0.8358075590975831, 0.5490663163770887, 0.5372003067386575]


In [ ]:
numeros = [111, 222, 333, 444, 555, 666, 777, 888, 999]

In [ ]:
#sorteia dentro da minha lista 4 números aleatórios
print(rd.sample(numeros, 4))

[666, 777, 888, 444]


In [ ]:
#embaralhe minha lista
rd.shuffle(numeros)
print(numeros)

[777, 888, 666, 999, 222, 444, 555, 333, 111]


In [ ]:
numeros

[777, 888, 666, 999, 222, 444, 555, 333, 111]

#pandas

In [ ]:
#estamos criando um arquivo que se chama data_acess.csv
#estou mudando de nome para não dar conflito com o 
#arquivo que eu tenho para data_acesso.csv
%%writefile data_acesso.csv  
day,month,num access,category
31,5,9241,student
31,5,830,teacher
31,5,45,coordinator
3,6,9102,student
3,6,1022,teacher
3,6,30,coordinator
4,6,10301,student
4,6,781,teacher
4,6,81,coordinator

Overwriting data_acesso.csv


In [ ]:
#preciso carregar o arquivo
import pandas as pd

#estou chamando o arquivo e carregando na minha variavel chamada df (data frame)
#o arquivo esta nesse caminho (olhe no menu na pasta)
df = pd.read_csv('/content/data_acesso.csv')

df

# o método read_csv carrega um arquivo no formato '.csv'
# a primeira linha do arquivo se torna os rótulos das colunas
# como os indices não foram especificados, são criados automaticamente

day  month  num access     category
0   31      5        9241      student
1   31      5         830      teacher
2   31      5          45  coordinator
3    3      6        9102      student
4    3      6        1022      teacher
5    3      6          30  coordinator
6    4      6       10301      student
7    4      6         781      teacher
8    4      6          81  coordinator

In [ ]:
df.head()

day  month  num access     category
0   31      5        9241      student
1   31      5         830      teacher
2   31      5          45  coordinator
3    3      6        9102      student
4    3      6        1022      teacher

In [ ]:
df.sample()

day  month  num access category
3    3      6        9102  student

In [ ]:
df.sample(4)

day  month  num access     category
2   31      5          45  coordinator
6    4      6       10301      student
8    4      6          81  coordinator
5    3      6          30  coordinator

In [ ]:
df.dtypes

day            int64
month          int64
num access     int64
category      object
dtype: object

In [ ]:
df.shape

(9, 4)

In [ ]:
df.columns

Index(['day', 'month', 'num access', 'category'], dtype='object')

#acessando uma coluna

In [ ]:
print(df['day'])

0    31
1    31
2    31
3     3
4     3
5     3
6     4
7     4
8     4
Name: day, dtype: int64


In [ ]:
print(df['day'])

0    31
1    31
2    31
3     3
4     3
5     3
6     4
7     4
8     4
Name: day, dtype: int64


In [ ]:
#não recomendado, pois pode haver colunas com o nome len
#df.len o que é um metodo, por isso não é recomendado
print(df.day)

0    31
1    31
2    31
3     3
4     3
5     3
6     4
7     4
8     4
Name: day, dtype: int64


In [ ]:
print(df['num access'])
#vai dar erro para print(df.num access) por causa do espaço

0     9241
1      830
2       45
3     9102
4     1022
5       30
6    10301
7      781
8       81
Name: num access, dtype: int64


#convertendo para valores


In [ ]:
lista_dias = list(df['day'].values)
print(lista_dias)

[31, 31, 31, 3, 3, 3, 4, 4, 4]


In [ ]:
#fazer buscas
df.query('month == 5')

day  month  num access     category
0   31      5        9241      student
1   31      5         830      teacher
2   31      5          45  coordinator

In [ ]:
df.query('month == 5 & category == "teacher"' )

day  month  num access category
1   31      5         830  teacher

In [ ]:
#dentro dessa linha eu só quero retornar o num access
df.query('month == 5 & category == "teacher"')['num access']

1    830
Name: num access, dtype: int64

#criando e removendo colunas

In [ ]:
df['year'] = 2021
df

day  month  num access     category  year
0   31      5        9241      student  2021
1   31      5         830      teacher  2021
2   31      5          45  coordinator  2021
3    3      6        9102      student  2021
4    3      6        1022      teacher  2021
5    3      6          30  coordinator  2021
6    4      6       10301      student  2021
7    4      6         781      teacher  2021
8    4      6          81  coordinator  2021

In [ ]:
#eu tenho uma lista, eu quero criar uma nova coluna com os valores dessa lista
lista = list(range(1, df.shape[0]+1))
df['id'] = lista
df

day  month  num access     category  year  id
0   31      5        9241      student  2021   1
1   31      5         830      teacher  2021   2
2   31      5          45  coordinator  2021   3
3    3      6        9102      student  2021   4
4    3      6        1022      teacher  2021   5
5    3      6          30  coordinator  2021   6
6    4      6       10301      student  2021   7
7    4      6         781      teacher  2021   8
8    4      6          81  coordinator  2021   9

In [ ]:
df = df.drop('month', axis=1)
print(df)

   day  num access     category  year  id
0   31        9241      student  2021   1
1   31         830      teacher  2021   2
2   31          45  coordinator  2021   3
3    3        9102      student  2021   4
4    3        1022      teacher  2021   5
5    3          30  coordinator  2021   6
6    4       10301      student  2021   7
7    4         781      teacher  2021   8
8    4          81  coordinator  2021   9


In [ ]:
df

day  num access     category  year  id
0   31        9241      student  2021   1
1   31         830      teacher  2021   2
2   31          45  coordinator  2021   3
3    3        9102      student  2021   4
4    3        1022      teacher  2021   5
5    3          30  coordinator  2021   6
6    4       10301      student  2021   7
7    4         781      teacher  2021   8
8    4          81  coordinator  2021   9

In [ ]:
del df['year']
df

day  num access     category  id
0   31        9241      student   1
1   31         830      teacher   2
2   31          45  coordinator   3
3    3        9102      student   4
4    3        1022      teacher   5
5    3          30  coordinator   6
6    4       10301      student   7
7    4         781      teacher   8
8    4          81  coordinator   9

#parte2

In [ ]:
%%writefile data_acesso.csv  
day,month,num access,category
31,5,9241,student
31,5,830,teacher
31,5,45,coordinator
3,6,9102,student
3,6,1022,teacher
3,6,30,coordinator
4,6,10301,student
4,6,781,teacher
4,6,81,coordinator

Overwriting data_acesso.csv


In [ ]:
import pandas as pd
df = pd.read_csv('/content/data_acesso.csv')
df

day  month  num access     category
0   31      5        9241      student
1   31      5         830      teacher
2   31      5          45  coordinator
3    3      6        9102      student
4    3      6        1022      teacher
5    3      6          30  coordinator
6    4      6       10301      student
7    4      6         781      teacher
8    4      6          81  coordinator

#acessando linhas

In [ ]:
#estou criando um indice que vai de 10 em 10
lista = list(range(10, (df.shape[0]+1)*10,10))
df['id'] = lista
df

day  month  num access     category  id
0   31      5        9241      student  10
1   31      5         830      teacher  20
2   31      5          45  coordinator  30
3    3      6        9102      student  40
4    3      6        1022      teacher  50
5    3      6          30  coordinator  60
6    4      6       10301      student  70
7    4      6         781      teacher  80
8    4      6          81  coordinator  90

In [ ]:
#eu quero que meu índice seja meu id
#não vai acontecer nada, pois não passei o implace
df.set_index('id')
df

day  month  num access     category  id
0   31      5        9241      student  10
1   31      5         830      teacher  20
2   31      5          45  coordinator  30
3    3      6        9102      student  40
4    3      6        1022      teacher  50
5    3      6          30  coordinator  60
6    4      6       10301      student  70
7    4      6         781      teacher  80
8    4      6          81  coordinator  90

In [ ]:
#agora com o implace
df.set_index('id', inplace=True)
df

day  month  num access     category
id                                     
10   31      5        9241      student
20   31      5         830      teacher
30   31      5          45  coordinator
40    3      6        9102      student
50    3      6        1022      teacher
60    3      6          30  coordinator
70    4      6       10301      student
80    4      6         781      teacher
90    4      6          81  coordinator

In [ ]:
#usando o loc
#com esse colchete a mais ele passa uma lista
df.loc[[20]]

day  month  num access category
id                                 
20   31      5         830  teacher

In [ ]:
df.loc[20]
#sem esse colchete a mais

day                31
month               5
num access        830
category      teacher
Name: 20, dtype: object

In [ ]:
df.loc[[90,10,30]]
#quento tem mais de uma linha, é necessario usar esses colchetes a mais

day  month  num access     category
id                                     
90    4      6          81  coordinator
10   31      5        9241      student
30   31      5          45  coordinator

In [ ]:
df.loc[10:40]
#do indice 10 até 40

day  month  num access     category
id                                     
10   31      5        9241      student
20   31      5         830      teacher
30   31      5          45  coordinator
40    3      6        9102      student

In [ ]:
df.loc[[10:40]]
#aqui não pode usar esses colchetes

SyntaxError: ignored

In [ ]:
#só quero uma linha, mas só me mostra day e month
df.loc[10:10, ['day', 'month']]

day  month
id            
10   31      5

In [ ]:
df.loc[10, ['day', 'month']]
#se eu tirar os dois pontos ele me retorna fora de uma lista

day      31
month     5
Name: 10, dtype: object

##condicional

In [ ]:
df['category'] == 'student'

id
10     True
20    False
30    False
40     True
50    False
60    False
70     True
80    False
90    False
Name: category, dtype: bool

In [ ]:
df.loc[df['category'] == 'student']

day  month  num access category
id                                 
10   31      5        9241  student
40    3      6        9102  student
70    4      6       10301  student

##iloc

In [ ]:
df

day  month  num access     category
id                                     
10   31      5        9241      student
20   31      5         830      teacher
30   31      5          45  coordinator
40    3      6        9102      student
50    3      6        1022      teacher
60    3      6          30  coordinator
70    4      6       10301      student
80    4      6         781      teacher
90    4      6          81  coordinator

In [ ]:
df.iloc[1]

day                31
month               5
num access        830
category      teacher
Name: 20, dtype: object

In [ ]:
cat_pos1 = df.iloc[1,3] #linha 1 coluna 3, lembrando que começa do zero
print(cat_pos1)

teacher


In [ ]:
#pegando todas as linhas com a referencia 3 que é colunas, categoty
#df.iloc[:,3] #sem o formato de lista
df.iloc[:,[3]]

category
id             
10      student
20      teacher
30  coordinator
40      student
50      teacher
60  coordinator
70      student
80      teacher
90  coordinator

In [ ]:
lista_cats = list(df.iloc[:, 3].values)
lista_cats

['student',
 'teacher',
 'coordinator',
 'student',
 'teacher',
 'coordinator',
 'student',
 'teacher',
 'coordinator']

In [ ]:
print(lista_cats)

['student', 'teacher', 'coordinator', 'student', 'teacher', 'coordinator', 'student', 'teacher', 'coordinator']


##fatiar

In [ ]:
df.iloc[3:5]

day  month  num access category
id                                 
40    3      6        9102  student
50    3      6        1022  teacher

In [ ]:
df.iloc[3:5, 2:3]

num access
id            
40        9102
50        1022

##retornando uma copia

In [ ]:
subdf1 = df.iloc[3:6, 2:]

In [ ]:
subdf1

num access     category
id                         
40        9102      student
50        1022      teacher
60          30  coordinator

In [ ]:
subdf1.iloc[2,0] = 1

In [ ]:
print(subdf1)

    num access     category
id                         
40        9102      student
50        1022      teacher
60           1  coordinator


In [ ]:
subdf1

num access     category
id                         
40        9102      student
50        1022      teacher
60           1  coordinator

In [ ]:
df

day  month  num access     category
id                                     
10   31      5        9241      student
20   31      5         830      teacher
30   31      5          45  coordinator
40    3      6        9102      student
50    3      6        1022      teacher
60    3      6          30  coordinator
70    4      6       10301      student
80    4      6         781      teacher
90    4      6          81  coordinator

In [ ]:
subdf2 = df.loc[40:60, ['num access', 'category']]

In [ ]:
subdf2

num access     category
id                         
40        9102      student
50        1022      teacher
60          30  coordinator

##estatistica


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/agronegocio/countries_data.tsv', sep='\t')

In [ ]:
df

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [ ]:
len(df.index)

1704

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [ ]:
df.sample(6)

country continent  year  lifeExp        pop     gdpPercap
962    Mauritania    Africa  1962   44.248    1146757   1055.896036
1386     Slovenia    Europe  1982   71.063    1861252  17866.721750
1473       Sweden    Europe  1997   79.390    8897619  25266.594990
1215  Philippines      Asia  1967   56.393   35356600   1814.127430
713     Indonesia      Asia  1977   52.702  136725000   1382.702056
1572       Turkey    Europe  1952   43.585   22235677   1969.100980

In [ ]:
df.head(10)

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945
8  Afghanistan      Asia  1992   41.674  16317921  649.341395
9  Afghanistan      Asia  1997   41.763  22227415  635.341351

In [ ]:
#média da população
df['pop'].mean()

29601212.324530516

In [ ]:
df.describe()

year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [ ]:
df[['lifeExp', 'pop', 'gdpPercap']].corr()
#corr() é a correlação entre eles

lifeExp       pop  gdpPercap
lifeExp    1.000000  0.064955   0.583706
pop        0.064955  1.000000  -0.025600
gdpPercap  0.583706 -0.025600   1.000000

#exercício

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/agronegocio/WorldCups.csv')
df

Year       Country      Winner       RunnersUp        Third  \
0   1930       Uruguay     Uruguay       Argentina          USA   
1   1934         Italy       Italy  Czechoslovakia      Germany   
2   1938        France       Italy         Hungary       Brazil   
3   1950        Brazil     Uruguay          Brazil       Sweden   
4   1954   Switzerland  Germany FR         Hungary      Austria   
5   1958        Sweden      Brazil          Sweden       France   
6   1962         Chile      Brazil  Czechoslovakia        Chile   
7   1966       England     England      Germany FR     Portugal   
8   1970        Mexico      Brazil           Italy   Germany FR   
9   1974       Germany  Germany FR     Netherlands       Poland   
10  1978     Argentina   Argentina     Netherlands       Brazil   
11  1982         Spain       Italy      Germany FR       Poland   
12  1986        Mexico   Argentina      Germany FR       France   
13  1990         Italy  Germany FR       Argentina        Italy   
14  1994           USA      Brazil           Italy       Sweden   
15  1998        France      France          Brazil      Croatia   
16  2002   Korea/Japan      Brazil         Germany       Turkey   
17  2006       Germany       Italy          France      Germany   
18  2010  South Africa       Spain     Netherlands      Germany   
19  2014        Brazil     Germany       Argentina  Netherlands   

            Fourth  GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  
0       Yugoslavia           70              13             18      590549  
1          Austria           70              16             17      363000  
2           Sweden           84              15             18      375700  
3            Spain           88              13             22     1045246  
4          Uruguay          140              16             26      768607  
5       Germany FR          126              16             35      819810  
6       Yugoslavia           89              16             32      893172  
7     Soviet Union           89              16             32     1563135  
8          Uruguay           95              16             32     1603975  
9           Brazil           97              16             38     1865753  
10           Italy          102              16             38     1545791  
11          France          146              24             52     2109723  
12         Belgium          132              24             52     2394031  
13         England          115              24             52     2516215  
14        Bulgaria          141              24             52     3587538  
15     Netherlands          171              32             64     2785100  
16  Korea Republic          161              32             64     2705197  
17        Portugal          147              32             64     3359439  
18         Uruguay          145              32             64     3178856  
19          Brazil          171              32             64     3386810

In [ ]:
df.set_index('Year', inplace=True)
df

Country      Winner       RunnersUp        Third          Fourth  \
Year                                                                          
1930       Uruguay     Uruguay       Argentina          USA      Yugoslavia   
1934         Italy       Italy  Czechoslovakia      Germany         Austria   
1938        France       Italy         Hungary       Brazil          Sweden   
1950        Brazil     Uruguay          Brazil       Sweden           Spain   
1954   Switzerland  Germany FR         Hungary      Austria         Uruguay   
1958        Sweden      Brazil          Sweden       France      Germany FR   
1962         Chile      Brazil  Czechoslovakia        Chile      Yugoslavia   
1966       England     England      Germany FR     Portugal    Soviet Union   
1970        Mexico      Brazil           Italy   Germany FR         Uruguay   
1974       Germany  Germany FR     Netherlands       Poland          Brazil   
1978     Argentina   Argentina     Netherlands       Brazil           Italy   
1982         Spain       Italy      Germany FR       Poland          France   
1986        Mexico   Argentina      Germany FR       France         Belgium   
1990         Italy  Germany FR       Argentina        Italy         England   
1994           USA      Brazil           Italy       Sweden        Bulgaria   
1998        France      France          Brazil      Croatia     Netherlands   
2002   Korea/Japan      Brazil         Germany       Turkey  Korea Republic   
2006       Germany       Italy          France      Germany        Portugal   
2010  South Africa       Spain     Netherlands      Germany         Uruguay   
2014        Brazil     Germany       Argentina  Netherlands          Brazil   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  
Year                                                          
1930           70              13             18      590549  
1934           70              16             17      363000  
1938           84              15             18      375700  
1950           88              13             22     1045246  
1954          140              16             26      768607  
1958          126              16             35      819810  
1962           89              16             32      893172  
1966           89              16             32     1563135  
1970           95              16             32     1603975  
1974           97              16             38     1865753  
1978          102              16             38     1545791  
1982          146              24             52     2109723  
1986          132              24             52     2394031  
1990          115              24             52     2516215  
1994          141              24             52     3587538  
1998          171              32             64     2785100  
2002          161              32             64     2705197  
2006          147              32             64     3359439  
2010          145              32             64     3178856  
2014          171              32             64     3386810

In [ ]:
df.head()

Country      Winner       RunnersUp    Third      Fourth  \
Year                                                                 
1930      Uruguay     Uruguay       Argentina      USA  Yugoslavia   
1934        Italy       Italy  Czechoslovakia  Germany     Austria   
1938       France       Italy         Hungary   Brazil      Sweden   
1950       Brazil     Uruguay          Brazil   Sweden       Spain   
1954  Switzerland  Germany FR         Hungary  Austria     Uruguay   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  
Year                                                          
1930           70              13             18      590549  
1934           70              16             17      363000  
1938           84              15             18      375700  
1950           88              13             22     1045246  
1954          140              16             26      768607

In [ ]:
# df.dtypes
print(df.dtypes)

Country           object
Winner            object
RunnersUp         object
Third             object
Fourth            object
GoalsScored        int64
QualifiedTeams     int64
MatchesPlayed      int64
Attendance         int64
dtype: object


In [ ]:
#contar a quantidades de linhas
# len(df.index) or
df.shape[0]

20

In [ ]:
# lista = list(range(1, df.shape[0]+1))
# df['id'] = lista
# df

In [ ]:
# df['AverageGoalsMatch'] = df.apply(lambda row: row.GoalsScored / row.MatchesPlayed, axis = 1) or
df['AverageGoalsMatch'] = df['GoalsScored'] / df['MatchesPlayed']

In [ ]:
df

Country      Winner       RunnersUp        Third          Fourth  \
Year                                                                          
1930       Uruguay     Uruguay       Argentina          USA      Yugoslavia   
1934         Italy       Italy  Czechoslovakia      Germany         Austria   
1938        France       Italy         Hungary       Brazil          Sweden   
1950        Brazil     Uruguay          Brazil       Sweden           Spain   
1954   Switzerland  Germany FR         Hungary      Austria         Uruguay   
1958        Sweden      Brazil          Sweden       France      Germany FR   
1962         Chile      Brazil  Czechoslovakia        Chile      Yugoslavia   
1966       England     England      Germany FR     Portugal    Soviet Union   
1970        Mexico      Brazil           Italy   Germany FR         Uruguay   
1974       Germany  Germany FR     Netherlands       Poland          Brazil   
1978     Argentina   Argentina     Netherlands       Brazil           Italy   
1982         Spain       Italy      Germany FR       Poland          France   
1986        Mexico   Argentina      Germany FR       France         Belgium   
1990         Italy  Germany FR       Argentina        Italy         England   
1994           USA      Brazil           Italy       Sweden        Bulgaria   
1998        France      France          Brazil      Croatia     Netherlands   
2002   Korea/Japan      Brazil         Germany       Turkey  Korea Republic   
2006       Germany       Italy          France      Germany        Portugal   
2010  South Africa       Spain     Netherlands      Germany         Uruguay   
2014        Brazil     Germany       Argentina  Netherlands          Brazil   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  \
Year                                                           
1930           70              13             18      590549   
1934           70              16             17      363000   
1938           84              15             18      375700   
1950           88              13             22     1045246   
1954          140              16             26      768607   
1958          126              16             35      819810   
1962           89              16             32      893172   
1966           89              16             32     1563135   
1970           95              16             32     1603975   
1974           97              16             38     1865753   
1978          102              16             38     1545791   
1982          146              24             52     2109723   
1986          132              24             52     2394031   
1990          115              24             52     2516215   
1994          141              24             52     3587538   
1998          171              32             64     2785100   
2002          161              32             64     2705197   
2006          147              32             64     3359439   
2010          145              32             64     3178856   
2014          171              32             64     3386810   

      AverageGoalsMatch  
Year                     
1930           3.888889  
1934           4.117647  
1938           4.666667  
1950           4.000000  
1954           5.384615  
1958           3.600000  
1962           2.781250  
1966           2.781250  
1970           2.968750  
1974           2.552632  
1978           2.684211  
1982           2.807692  
1986           2.538462  
1990           2.211538  
1994           2.711538  
1998           2.671875  
2002           2.515625  
2006           2.296875  
2010           2.265625  
2014           2.671875

In [ ]:
df2 = df.loc[df['Winner'] == 'Brazil']
df2

Country  Winner       RunnersUp       Third          Fourth  \
Year                                                                    
1958       Sweden  Brazil          Sweden      France      Germany FR   
1962        Chile  Brazil  Czechoslovakia       Chile      Yugoslavia   
1970       Mexico  Brazil           Italy  Germany FR         Uruguay   
1994          USA  Brazil           Italy      Sweden        Bulgaria   
2002  Korea/Japan  Brazil         Germany      Turkey  Korea Republic   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  \
Year                                                           
1958          126              16             35      819810   
1962           89              16             32      893172   
1970           95              16             32     1603975   
1994          141              24             52     3587538   
2002          161              32             64     2705197   

      AverageGoalsMatch  
Year                     
1958           3.600000  
1962           2.781250  
1970           2.968750  
1994           2.711538  
2002           2.515625

In [ ]:
df2['AverageGoalsMatch'].mean()

2.915432692307692

In [ ]:
lista_media = list(df2['AverageGoalsMatch'].values)
lista_media

[3.6, 2.78125, 2.96875, 2.7115384615384617, 2.515625]

In [ ]:
# df.query('month == 5 & category == "teacher"')['num access']
df3 = df.query('Winner == "Brazil" | RunnersUp == "Brazil"')
#df3 = df.loc[df['Winner & RunnersUp'] == 'Brazil']
df3

Country   Winner       RunnersUp       Third          Fourth  \
Year                                                                     
1950       Brazil  Uruguay          Brazil      Sweden           Spain   
1958       Sweden   Brazil          Sweden      France      Germany FR   
1962        Chile   Brazil  Czechoslovakia       Chile      Yugoslavia   
1970       Mexico   Brazil           Italy  Germany FR         Uruguay   
1994          USA   Brazil           Italy      Sweden        Bulgaria   
1998       France   France          Brazil     Croatia     Netherlands   
2002  Korea/Japan   Brazil         Germany      Turkey  Korea Republic   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  \
Year                                                           
1950           88              13             22     1045246   
1958          126              16             35      819810   
1962           89              16             32      893172   
1970           95              16             32     1603975   
1994          141              24             52     3587538   
1998          171              32             64     2785100   
2002          161              32             64     2705197   

      AverageGoalsMatch  
Year                     
1950           4.000000  
1958           3.600000  
1962           2.781250  
1970           2.968750  
1994           2.711538  
1998           2.671875  
2002           2.515625

In [ ]:
df3['AverageGoalsMatch']

Year
1950    4.000000
1958    3.600000
1962    2.781250
1970    2.968750
1994    2.711538
1998    2.671875
2002    2.515625
Name: AverageGoalsMatch, dtype: float64

#Resolução

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/agronegocio/WorldCups.csv')
df

Year       Country      Winner       RunnersUp        Third  \
0   1930       Uruguay     Uruguay       Argentina          USA   
1   1934         Italy       Italy  Czechoslovakia      Germany   
2   1938        France       Italy         Hungary       Brazil   
3   1950        Brazil     Uruguay          Brazil       Sweden   
4   1954   Switzerland  Germany FR         Hungary      Austria   
5   1958        Sweden      Brazil          Sweden       France   
6   1962         Chile      Brazil  Czechoslovakia        Chile   
7   1966       England     England      Germany FR     Portugal   
8   1970        Mexico      Brazil           Italy   Germany FR   
9   1974       Germany  Germany FR     Netherlands       Poland   
10  1978     Argentina   Argentina     Netherlands       Brazil   
11  1982         Spain       Italy      Germany FR       Poland   
12  1986        Mexico   Argentina      Germany FR       France   
13  1990         Italy  Germany FR       Argentina        Italy   
14  1994           USA      Brazil           Italy       Sweden   
15  1998        France      France          Brazil      Croatia   
16  2002   Korea/Japan      Brazil         Germany       Turkey   
17  2006       Germany       Italy          France      Germany   
18  2010  South Africa       Spain     Netherlands      Germany   
19  2014        Brazil     Germany       Argentina  Netherlands   

            Fourth  GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  
0       Yugoslavia           70              13             18      590549  
1          Austria           70              16             17      363000  
2           Sweden           84              15             18      375700  
3            Spain           88              13             22     1045246  
4          Uruguay          140              16             26      768607  
5       Germany FR          126              16             35      819810  
6       Yugoslavia           89              16             32      893172  
7     Soviet Union           89              16             32     1563135  
8          Uruguay           95              16             32     1603975  
9           Brazil           97              16             38     1865753  
10           Italy          102              16             38     1545791  
11          France          146              24             52     2109723  
12         Belgium          132              24             52     2394031  
13         England          115              24             52     2516215  
14        Bulgaria          141              24             52     3587538  
15     Netherlands          171              32             64     2785100  
16  Korea Republic          161              32             64     2705197  
17        Portugal          147              32             64     3359439  
18         Uruguay          145              32             64     3178856  
19          Brazil          171              32             64     3386810

In [ ]:
df.set_index('Year', inplace=True)
df

Country      Winner       RunnersUp        Third          Fourth  \
Year                                                                          
1930       Uruguay     Uruguay       Argentina          USA      Yugoslavia   
1934         Italy       Italy  Czechoslovakia      Germany         Austria   
1938        France       Italy         Hungary       Brazil          Sweden   
1950        Brazil     Uruguay          Brazil       Sweden           Spain   
1954   Switzerland  Germany FR         Hungary      Austria         Uruguay   
1958        Sweden      Brazil          Sweden       France      Germany FR   
1962         Chile      Brazil  Czechoslovakia        Chile      Yugoslavia   
1966       England     England      Germany FR     Portugal    Soviet Union   
1970        Mexico      Brazil           Italy   Germany FR         Uruguay   
1974       Germany  Germany FR     Netherlands       Poland          Brazil   
1978     Argentina   Argentina     Netherlands       Brazil           Italy   
1982         Spain       Italy      Germany FR       Poland          France   
1986        Mexico   Argentina      Germany FR       France         Belgium   
1990         Italy  Germany FR       Argentina        Italy         England   
1994           USA      Brazil           Italy       Sweden        Bulgaria   
1998        France      France          Brazil      Croatia     Netherlands   
2002   Korea/Japan      Brazil         Germany       Turkey  Korea Republic   
2006       Germany       Italy          France      Germany        Portugal   
2010  South Africa       Spain     Netherlands      Germany         Uruguay   
2014        Brazil     Germany       Argentina  Netherlands          Brazil   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  
Year                                                          
1930           70              13             18      590549  
1934           70              16             17      363000  
1938           84              15             18      375700  
1950           88              13             22     1045246  
1954          140              16             26      768607  
1958          126              16             35      819810  
1962           89              16             32      893172  
1966           89              16             32     1563135  
1970           95              16             32     1603975  
1974           97              16             38     1865753  
1978          102              16             38     1545791  
1982          146              24             52     2109723  
1986          132              24             52     2394031  
1990          115              24             52     2516215  
1994          141              24             52     3587538  
1998          171              32             64     2785100  
2002          161              32             64     2705197  
2006          147              32             64     3359439  
2010          145              32             64     3178856  
2014          171              32             64     3386810

In [ ]:
df.shape[0]

20

In [ ]:
df['AverageGoalsMatch'] = df['GoalsScored']/df['MatchesPlayed']
df

Country      Winner       RunnersUp        Third          Fourth  \
Year                                                                          
1930       Uruguay     Uruguay       Argentina          USA      Yugoslavia   
1934         Italy       Italy  Czechoslovakia      Germany         Austria   
1938        France       Italy         Hungary       Brazil          Sweden   
1950        Brazil     Uruguay          Brazil       Sweden           Spain   
1954   Switzerland  Germany FR         Hungary      Austria         Uruguay   
1958        Sweden      Brazil          Sweden       France      Germany FR   
1962         Chile      Brazil  Czechoslovakia        Chile      Yugoslavia   
1966       England     England      Germany FR     Portugal    Soviet Union   
1970        Mexico      Brazil           Italy   Germany FR         Uruguay   
1974       Germany  Germany FR     Netherlands       Poland          Brazil   
1978     Argentina   Argentina     Netherlands       Brazil           Italy   
1982         Spain       Italy      Germany FR       Poland          France   
1986        Mexico   Argentina      Germany FR       France         Belgium   
1990         Italy  Germany FR       Argentina        Italy         England   
1994           USA      Brazil           Italy       Sweden        Bulgaria   
1998        France      France          Brazil      Croatia     Netherlands   
2002   Korea/Japan      Brazil         Germany       Turkey  Korea Republic   
2006       Germany       Italy          France      Germany        Portugal   
2010  South Africa       Spain     Netherlands      Germany         Uruguay   
2014        Brazil     Germany       Argentina  Netherlands          Brazil   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  \
Year                                                           
1930           70              13             18      590549   
1934           70              16             17      363000   
1938           84              15             18      375700   
1950           88              13             22     1045246   
1954          140              16             26      768607   
1958          126              16             35      819810   
1962           89              16             32      893172   
1966           89              16             32     1563135   
1970           95              16             32     1603975   
1974           97              16             38     1865753   
1978          102              16             38     1545791   
1982          146              24             52     2109723   
1986          132              24             52     2394031   
1990          115              24             52     2516215   
1994          141              24             52     3587538   
1998          171              32             64     2785100   
2002          161              32             64     2705197   
2006          147              32             64     3359439   
2010          145              32             64     3178856   
2014          171              32             64     3386810   

      AverageGoalsMatch  
Year                     
1930           3.888889  
1934           4.117647  
1938           4.666667  
1950           4.000000  
1954           5.384615  
1958           3.600000  
1962           2.781250  
1966           2.781250  
1970           2.968750  
1974           2.552632  
1978           2.684211  
1982           2.807692  
1986           2.538462  
1990           2.211538  
1994           2.711538  
1998           2.671875  
2002           2.515625  
2006           2.296875  
2010           2.265625  
2014           2.671875

In [ ]:
ganhou = df.query('Winner == "Brazil"')
participou = df.query('Winner == "Brazil" | RunnersUp == "Brazil"')

In [ ]:
ganhou

Country  Winner       RunnersUp       Third          Fourth  \
Year                                                                    
1958       Sweden  Brazil          Sweden      France      Germany FR   
1962        Chile  Brazil  Czechoslovakia       Chile      Yugoslavia   
1970       Mexico  Brazil           Italy  Germany FR         Uruguay   
1994          USA  Brazil           Italy      Sweden        Bulgaria   
2002  Korea/Japan  Brazil         Germany      Turkey  Korea Republic   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  \
Year                                                           
1958          126              16             35      819810   
1962           89              16             32      893172   
1970           95              16             32     1603975   
1994          141              24             52     3587538   
2002          161              32             64     2705197   

      AverageGoalsMatch  
Year                     
1958           3.600000  
1962           2.781250  
1970           2.968750  
1994           2.711538  
2002           2.515625

In [ ]:
participou

Country   Winner       RunnersUp       Third          Fourth  \
Year                                                                     
1950       Brazil  Uruguay          Brazil      Sweden           Spain   
1958       Sweden   Brazil          Sweden      France      Germany FR   
1962        Chile   Brazil  Czechoslovakia       Chile      Yugoslavia   
1970       Mexico   Brazil           Italy  Germany FR         Uruguay   
1994          USA   Brazil           Italy      Sweden        Bulgaria   
1998       France   France          Brazil     Croatia     Netherlands   
2002  Korea/Japan   Brazil         Germany      Turkey  Korea Republic   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  \
Year                                                           
1950           88              13             22     1045246   
1958          126              16             35      819810   
1962           89              16             32      893172   
1970           95              16             32     1603975   
1994          141              24             52     3587538   
1998          171              32             64     2785100   
2002          161              32             64     2705197   

      AverageGoalsMatch  
Year                     
1950           4.000000  
1958           3.600000  
1962           2.781250  
1970           2.968750  
1994           2.711538  
1998           2.671875  
2002           2.515625

In [ ]:
lista_media_gols = list(ganhou['AverageGoalsMatch'].values)
lista_media_gols

[3.6, 2.78125, 2.96875, 2.7115384615384617, 2.515625]

In [ ]:
participou['AverageGoalsMatch']

Year
1950    4.000000
1958    3.600000
1962    2.781250
1970    2.968750
1994    2.711538
1998    2.671875
2002    2.515625
Name: AverageGoalsMatch, dtype: float64

In [ ]:
round((ganhou.shape[0] / participou.shape[0])*100,1)

71.4

In [ ]:
# para verificar somente os anos, olhamos somente os rótulos dos DataFrames acima
lista_media_gols = list(ganhou['AverageGoalsMatch'].values)
print('média de gols nos anos que ganhou:', lista_media_gols)    # anos em que o Brasil venceu

print('\nanos em que foi para a final e média de gols:')
print(participou['AverageGoalsMatch']) # anos em que o Brasil disputou uma final

# basta dividimos o número de disputas de final pelo número de vitórias
print('\nporcentagem de vitórias em finais:', round((ganhou.shape[0] / participou.shape[0])*100,3), '%') 

média de gols nos anos que ganhou: [3.6, 2.78125, 2.96875, 2.7115384615384617, 2.515625]

anos em que foi para a final e média de gols:
Year
1950    4.000000
1958    3.600000
1962    2.781250
1970    2.968750
1994    2.711538
1998    2.671875
2002    2.515625
Name: AverageGoalsMatch, dtype: float64

porcentagem de vitórias em finais: 71.429 %


#numpy

In [1]:
import numpy as np

# array com oito elementos iguais a zero
b1d = np.zeros((8))  
print('Zeros: ',b1d)

# array com dez elementos iguais a um
c1d = np.ones((10))  
print('Ones: ',c1d)

# array com numeros entre 1 e menor que 11, com passo 2 (similar a `range`)
d1d = np.arange(0,11,2)  
print('Range: ',d1d)

# array com 5 números igualmente espaçados no intervalo entre 1 e 2 
e1d = np.linspace(1,2,5) 
print('Linspace: ',e1d)

e1d2 = np.linspace(0,1,101) 
print('Linspace2: ',e1d2)

Zeros:  [0. 0. 0. 0. 0. 0. 0. 0.]
Ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Range:  [ 0  2  4  6  8 10]
Linspace:  [1.   1.25 1.5  1.75 2.  ]
Linspace2:  [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


### arrays multidimensionais

In [2]:
a2d = np.array([[1,3,5,7,8,11], [2,4,6,8,10,12], [0,1,2,3,4,5]])
print('a2d=\n', a2d)

a2d=
 [[ 1  3  5  7  8 11]
 [ 2  4  6  8 10 12]
 [ 0  1  2  3  4  5]]


In [3]:
#matriz 5X3 de zeros
b2d = np.zeros((5,3))  
print('Zeros 2d: \n',b2d)

# criando matriz 4X8 de 1s
c2d = np.ones((4,8))
print('Ones 2d:\n',c2d)

# criando matrix identidade 3X3
d2d = np.identity(5) 
print('Identity: \n',d2d)

Zeros 2d: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones 2d:
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
Identity: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
a1d = np.array([1,3,5,7,11])
print(a1d)
print(c2d)

[ 1  3  5  7 11]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Arrays são objetos _ndarrays_ 

Seus atributos são: 
- `ndarray.ndim`: número de eixos (dimensões) do array
- `ndarray.shape`: uma tupla de inteiros indicando o tamanho do array em cada dimensão
- `ndarray.size`:  o número total de elementos do array
- `ndarray.dtype`: tipo dos elementos no array
- `ndarray.itemsize`: o tamanho em bytes de cada elemento do array
- `ndarray.T`: versão transposta do array

In [13]:
print(" ndim: numero de eixos dos arrays")
print('a1d.ndim =',a1d.ndim)
print('c2d.ndim =',c2d.ndim)

 ndim: numero de eixos dos arrays
a1d.ndim = 1
c2d.ndim = 2


In [14]:
print("\n shape: tamanho do array em cada dimensao")
print('a1d.shape =',a1d.shape)
print('b1d.shape =',b1d.shape)
print('a2d.shape =',a2d.shape)
print('c2d.shape =',c2d.shape)


 shape: tamanho do array em cada dimensao
a1d.shape = (5,)
b1d.shape = (8,)
a2d.shape = (3, 6)
c2d.shape = (4, 8)


In [15]:
print("\n size: numero total de elementos")
print('a1d.size =',a1d.size)
print('b1d.size =',b1d.size)
print('a2d.size =',a2d.size)
print('c2d.size =',c2d.size)


 size: numero total de elementos
a1d.size = 5
b1d.size = 8
a2d.size = 18
c2d.size = 32


In [16]:
print("\n dtype: tipo dos elementos")
print('a1d.dtype =',a1d.dtype)
print('b1d.dtype =',b1d.dtype)
print('a2d.dtype =',a2d.dtype)
print('c2d.dtype =',c2d.dtype)


 dtype: tipo dos elementos
a1d.dtype = int64
b1d.dtype = float64
a2d.dtype = int64
c2d.dtype = float64


In [17]:
print("\n itemsize: tamanho em bytes de cada elemento")
print('a1d.itemsize =',a1d.itemsize)
print('b1d.itemsize =',b1d.itemsize)
print('a2d.itemsize =',a2d.itemsize)
print('c2d.itemsize =',c2d.itemsize)


 itemsize: tamanho em bytes de cada elemento
a1d.itemsize = 8
b1d.itemsize = 8
a2d.itemsize = 8
c2d.itemsize = 8
